"""baseline schema

Revision ID: 4101b960b879
Revises: 
Create Date: 2026-09-20 13:55:42.255253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app.db.models.types


# revision identifiers, used by Alembic.
revision: str = '4101b960b879'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_etag',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', app.db.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('guruvani',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_ml', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guruvani_sort_order'), 'guruvani', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guruvani_sort_order'), table_name='guruvani')
    op.drop_table('guruvani')
    op.drop_table('dataset_etag')
    # ### end Alembic commands ###
