from __future__ import annotations

from typing import Protocol

from typing_extensions import Self


class UnitOfWork(Protocol):
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
